apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: f4i-tv-homethermometer
spec:
  selector:
    matchLabels:
      app: f4i-homethermometer
  replicas: 1
  template:
    metadata:
      labels:
        app: f4i-homethermometer
    spec:
      containers:
      - name: f4i-homethermometer
        image: domussapiens/homethermometer-tv:latest
        ports:
        - containerPort: 8089
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-tv-svc-homethermometer
  labels:
    app: f4i-homethermometer
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort:
    nodePort:
  selector:
    app: f4i-homethermometer